require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConsumableMaterialsController do

  # This should return the minimal set of attributes required to create a valid
  # ConsumableMaterial. As you add validations to ConsumableMaterial, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "product_type" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConsumableMaterialsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all consumable_materials as @consumable_materials" do
      consumable_material = ConsumableMaterial.create! valid_attributes
      get :index, {}, valid_session
      assigns(:consumable_materials).should eq([consumable_material])
    end
  end

  describe "GET show" do
    it "assigns the requested consumable_material as @consumable_material" do
      consumable_material = ConsumableMaterial.create! valid_attributes
      get :show, {:id => consumable_material.to_param}, valid_session
      assigns(:consumable_material).should eq(consumable_material)
    end
  end

  describe "GET new" do
    it "assigns a new consumable_material as @consumable_material" do
      get :new, {}, valid_session
      assigns(:consumable_material).should be_a_new(ConsumableMaterial)
    end
  end

  describe "GET edit" do
    it "assigns the requested consumable_material as @consumable_material" do
      consumable_material = ConsumableMaterial.create! valid_attributes
      get :edit, {:id => consumable_material.to_param}, valid_session
      assigns(:consumable_material).should eq(consumable_material)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ConsumableMaterial" do
        expect {
          post :create, {:consumable_material => valid_attributes}, valid_session
        }.to change(ConsumableMaterial, :count).by(1)
      end

      it "assigns a newly created consumable_material as @consumable_material" do
        post :create, {:consumable_material => valid_attributes}, valid_session
        assigns(:consumable_material).should be_a(ConsumableMaterial)
        assigns(:consumable_material).should be_persisted
      end

      it "redirects to the created consumable_material" do
        post :create, {:consumable_material => valid_attributes}, valid_session
        response.should redirect_to(ConsumableMaterial.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved consumable_material as @consumable_material" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumableMaterial.any_instance.stub(:save).and_return(false)
        post :create, {:consumable_material => { "product_type" => "invalid value" }}, valid_session
        assigns(:consumable_material).should be_a_new(ConsumableMaterial)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumableMaterial.any_instance.stub(:save).and_return(false)
        post :create, {:consumable_material => { "product_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested consumable_material" do
        consumable_material = ConsumableMaterial.create! valid_attributes
        # Assuming there are no other consumable_materials in the database, this
        # specifies that the ConsumableMaterial created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ConsumableMaterial.any_instance.should_receive(:update).with({ "product_type" => "MyString" })
        put :update, {:id => consumable_material.to_param, :consumable_material => { "product_type" => "MyString" }}, valid_session
      end

      it "assigns the requested consumable_material as @consumable_material" do
        consumable_material = ConsumableMaterial.create! valid_attributes
        put :update, {:id => consumable_material.to_param, :consumable_material => valid_attributes}, valid_session
        assigns(:consumable_material).should eq(consumable_material)
      end

      it "redirects to the consumable_material" do
        consumable_material = ConsumableMaterial.create! valid_attributes
        put :update, {:id => consumable_material.to_param, :consumable_material => valid_attributes}, valid_session
        response.should redirect_to(consumable_material)
      end
    end

    describe "with invalid params" do
      it "assigns the consumable_material as @consumable_material" do
        consumable_material = ConsumableMaterial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumableMaterial.any_instance.stub(:save).and_return(false)
        put :update, {:id => consumable_material.to_param, :consumable_material => { "product_type" => "invalid value" }}, valid_session
        assigns(:consumable_material).should eq(consumable_material)
      end

      it "re-renders the 'edit' template" do
        consumable_material = ConsumableMaterial.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ConsumableMaterial.any_instance.stub(:save).and_return(false)
        put :update, {:id => consumable_material.to_param, :consumable_material => { "product_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested consumable_material" do
      consumable_material = ConsumableMaterial.create! valid_attributes
      expect {
        delete :destroy, {:id => consumable_material.to_param}, valid_session
      }.to change(ConsumableMaterial, :count).by(-1)
    end

    it "redirects to the consumable_materials list" do
      consumable_material = ConsumableMaterial.create! valid_attributes
      delete :destroy, {:id => consumable_material.to_param}, valid_session
      response.should redirect_to(consumable_materials_url)
    end
  end

end
