require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IpcSeatsController do

  # This should return the minimal set of attributes required to create a valid
  # IpcSeat. As you add validations to IpcSeat, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "manufacturer" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IpcSeatsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ipc_seats as @ipc_seats" do
      ipc_seat = IpcSeat.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ipc_seats).should eq([ipc_seat])
    end
  end

  describe "GET show" do
    it "assigns the requested ipc_seat as @ipc_seat" do
      ipc_seat = IpcSeat.create! valid_attributes
      get :show, {:id => ipc_seat.to_param}, valid_session
      assigns(:ipc_seat).should eq(ipc_seat)
    end
  end

  describe "GET new" do
    it "assigns a new ipc_seat as @ipc_seat" do
      get :new, {}, valid_session
      assigns(:ipc_seat).should be_a_new(IpcSeat)
    end
  end

  describe "GET edit" do
    it "assigns the requested ipc_seat as @ipc_seat" do
      ipc_seat = IpcSeat.create! valid_attributes
      get :edit, {:id => ipc_seat.to_param}, valid_session
      assigns(:ipc_seat).should eq(ipc_seat)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IpcSeat" do
        expect {
          post :create, {:ipc_seat => valid_attributes}, valid_session
        }.to change(IpcSeat, :count).by(1)
      end

      it "assigns a newly created ipc_seat as @ipc_seat" do
        post :create, {:ipc_seat => valid_attributes}, valid_session
        assigns(:ipc_seat).should be_a(IpcSeat)
        assigns(:ipc_seat).should be_persisted
      end

      it "redirects to the created ipc_seat" do
        post :create, {:ipc_seat => valid_attributes}, valid_session
        response.should redirect_to(IpcSeat.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ipc_seat as @ipc_seat" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpcSeat.any_instance.stub(:save).and_return(false)
        post :create, {:ipc_seat => { "manufacturer" => "invalid value" }}, valid_session
        assigns(:ipc_seat).should be_a_new(IpcSeat)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpcSeat.any_instance.stub(:save).and_return(false)
        post :create, {:ipc_seat => { "manufacturer" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ipc_seat" do
        ipc_seat = IpcSeat.create! valid_attributes
        # Assuming there are no other ipc_seats in the database, this
        # specifies that the IpcSeat created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IpcSeat.any_instance.should_receive(:update).with({ "manufacturer" => "MyString" })
        put :update, {:id => ipc_seat.to_param, :ipc_seat => { "manufacturer" => "MyString" }}, valid_session
      end

      it "assigns the requested ipc_seat as @ipc_seat" do
        ipc_seat = IpcSeat.create! valid_attributes
        put :update, {:id => ipc_seat.to_param, :ipc_seat => valid_attributes}, valid_session
        assigns(:ipc_seat).should eq(ipc_seat)
      end

      it "redirects to the ipc_seat" do
        ipc_seat = IpcSeat.create! valid_attributes
        put :update, {:id => ipc_seat.to_param, :ipc_seat => valid_attributes}, valid_session
        response.should redirect_to(ipc_seat)
      end
    end

    describe "with invalid params" do
      it "assigns the ipc_seat as @ipc_seat" do
        ipc_seat = IpcSeat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpcSeat.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipc_seat.to_param, :ipc_seat => { "manufacturer" => "invalid value" }}, valid_session
        assigns(:ipc_seat).should eq(ipc_seat)
      end

      it "re-renders the 'edit' template" do
        ipc_seat = IpcSeat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpcSeat.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipc_seat.to_param, :ipc_seat => { "manufacturer" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ipc_seat" do
      ipc_seat = IpcSeat.create! valid_attributes
      expect {
        delete :destroy, {:id => ipc_seat.to_param}, valid_session
      }.to change(IpcSeat, :count).by(-1)
    end

    it "redirects to the ipc_seats list" do
      ipc_seat = IpcSeat.create! valid_attributes
      delete :destroy, {:id => ipc_seat.to_param}, valid_session
      response.should redirect_to(ipc_seats_url)
    end
  end

end
