require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IpcAllAcsController do

  # This should return the minimal set of attributes required to create a valid
  # IpcAllAc. As you add validations to IpcAllAc, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "system" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IpcAllAcsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ipc_all_acs as @ipc_all_acs" do
      ipc_all_ac = IpcAllAc.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ipc_all_acs).should eq([ipc_all_ac])
    end
  end

  describe "GET show" do
    it "assigns the requested ipc_all_ac as @ipc_all_ac" do
      ipc_all_ac = IpcAllAc.create! valid_attributes
      get :show, {:id => ipc_all_ac.to_param}, valid_session
      assigns(:ipc_all_ac).should eq(ipc_all_ac)
    end
  end

  describe "GET new" do
    it "assigns a new ipc_all_ac as @ipc_all_ac" do
      get :new, {}, valid_session
      assigns(:ipc_all_ac).should be_a_new(IpcAllAc)
    end
  end

  describe "GET edit" do
    it "assigns the requested ipc_all_ac as @ipc_all_ac" do
      ipc_all_ac = IpcAllAc.create! valid_attributes
      get :edit, {:id => ipc_all_ac.to_param}, valid_session
      assigns(:ipc_all_ac).should eq(ipc_all_ac)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IpcAllAc" do
        expect {
          post :create, {:ipc_all_ac => valid_attributes}, valid_session
        }.to change(IpcAllAc, :count).by(1)
      end

      it "assigns a newly created ipc_all_ac as @ipc_all_ac" do
        post :create, {:ipc_all_ac => valid_attributes}, valid_session
        assigns(:ipc_all_ac).should be_a(IpcAllAc)
        assigns(:ipc_all_ac).should be_persisted
      end

      it "redirects to the created ipc_all_ac" do
        post :create, {:ipc_all_ac => valid_attributes}, valid_session
        response.should redirect_to(IpcAllAc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ipc_all_ac as @ipc_all_ac" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpcAllAc.any_instance.stub(:save).and_return(false)
        post :create, {:ipc_all_ac => { "system" => "invalid value" }}, valid_session
        assigns(:ipc_all_ac).should be_a_new(IpcAllAc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpcAllAc.any_instance.stub(:save).and_return(false)
        post :create, {:ipc_all_ac => { "system" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ipc_all_ac" do
        ipc_all_ac = IpcAllAc.create! valid_attributes
        # Assuming there are no other ipc_all_acs in the database, this
        # specifies that the IpcAllAc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IpcAllAc.any_instance.should_receive(:update).with({ "system" => "MyString" })
        put :update, {:id => ipc_all_ac.to_param, :ipc_all_ac => { "system" => "MyString" }}, valid_session
      end

      it "assigns the requested ipc_all_ac as @ipc_all_ac" do
        ipc_all_ac = IpcAllAc.create! valid_attributes
        put :update, {:id => ipc_all_ac.to_param, :ipc_all_ac => valid_attributes}, valid_session
        assigns(:ipc_all_ac).should eq(ipc_all_ac)
      end

      it "redirects to the ipc_all_ac" do
        ipc_all_ac = IpcAllAc.create! valid_attributes
        put :update, {:id => ipc_all_ac.to_param, :ipc_all_ac => valid_attributes}, valid_session
        response.should redirect_to(ipc_all_ac)
      end
    end

    describe "with invalid params" do
      it "assigns the ipc_all_ac as @ipc_all_ac" do
        ipc_all_ac = IpcAllAc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpcAllAc.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipc_all_ac.to_param, :ipc_all_ac => { "system" => "invalid value" }}, valid_session
        assigns(:ipc_all_ac).should eq(ipc_all_ac)
      end

      it "re-renders the 'edit' template" do
        ipc_all_ac = IpcAllAc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpcAllAc.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipc_all_ac.to_param, :ipc_all_ac => { "system" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ipc_all_ac" do
      ipc_all_ac = IpcAllAc.create! valid_attributes
      expect {
        delete :destroy, {:id => ipc_all_ac.to_param}, valid_session
      }.to change(IpcAllAc, :count).by(-1)
    end

    it "redirects to the ipc_all_acs list" do
      ipc_all_ac = IpcAllAc.create! valid_attributes
      delete :destroy, {:id => ipc_all_ac.to_param}, valid_session
      response.should redirect_to(ipc_all_acs_url)
    end
  end

end
