require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe IpcBoeingsController do

  # This should return the minimal set of attributes required to create a valid
  # IpcBoeing. As you add validations to IpcBoeing, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ac_type" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IpcBoeingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ipc_boeings as @ipc_boeings" do
      ipc_boeing = IpcBoeing.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ipc_boeings).should eq([ipc_boeing])
    end
  end

  describe "GET show" do
    it "assigns the requested ipc_boeing as @ipc_boeing" do
      ipc_boeing = IpcBoeing.create! valid_attributes
      get :show, {:id => ipc_boeing.to_param}, valid_session
      assigns(:ipc_boeing).should eq(ipc_boeing)
    end
  end

  describe "GET new" do
    it "assigns a new ipc_boeing as @ipc_boeing" do
      get :new, {}, valid_session
      assigns(:ipc_boeing).should be_a_new(IpcBoeing)
    end
  end

  describe "GET edit" do
    it "assigns the requested ipc_boeing as @ipc_boeing" do
      ipc_boeing = IpcBoeing.create! valid_attributes
      get :edit, {:id => ipc_boeing.to_param}, valid_session
      assigns(:ipc_boeing).should eq(ipc_boeing)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new IpcBoeing" do
        expect {
          post :create, {:ipc_boeing => valid_attributes}, valid_session
        }.to change(IpcBoeing, :count).by(1)
      end

      it "assigns a newly created ipc_boeing as @ipc_boeing" do
        post :create, {:ipc_boeing => valid_attributes}, valid_session
        assigns(:ipc_boeing).should be_a(IpcBoeing)
        assigns(:ipc_boeing).should be_persisted
      end

      it "redirects to the created ipc_boeing" do
        post :create, {:ipc_boeing => valid_attributes}, valid_session
        response.should redirect_to(IpcBoeing.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ipc_boeing as @ipc_boeing" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpcBoeing.any_instance.stub(:save).and_return(false)
        post :create, {:ipc_boeing => { "ac_type" => "invalid value" }}, valid_session
        assigns(:ipc_boeing).should be_a_new(IpcBoeing)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        IpcBoeing.any_instance.stub(:save).and_return(false)
        post :create, {:ipc_boeing => { "ac_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ipc_boeing" do
        ipc_boeing = IpcBoeing.create! valid_attributes
        # Assuming there are no other ipc_boeings in the database, this
        # specifies that the IpcBoeing created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        IpcBoeing.any_instance.should_receive(:update).with({ "ac_type" => "MyString" })
        put :update, {:id => ipc_boeing.to_param, :ipc_boeing => { "ac_type" => "MyString" }}, valid_session
      end

      it "assigns the requested ipc_boeing as @ipc_boeing" do
        ipc_boeing = IpcBoeing.create! valid_attributes
        put :update, {:id => ipc_boeing.to_param, :ipc_boeing => valid_attributes}, valid_session
        assigns(:ipc_boeing).should eq(ipc_boeing)
      end

      it "redirects to the ipc_boeing" do
        ipc_boeing = IpcBoeing.create! valid_attributes
        put :update, {:id => ipc_boeing.to_param, :ipc_boeing => valid_attributes}, valid_session
        response.should redirect_to(ipc_boeing)
      end
    end

    describe "with invalid params" do
      it "assigns the ipc_boeing as @ipc_boeing" do
        ipc_boeing = IpcBoeing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpcBoeing.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipc_boeing.to_param, :ipc_boeing => { "ac_type" => "invalid value" }}, valid_session
        assigns(:ipc_boeing).should eq(ipc_boeing)
      end

      it "re-renders the 'edit' template" do
        ipc_boeing = IpcBoeing.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        IpcBoeing.any_instance.stub(:save).and_return(false)
        put :update, {:id => ipc_boeing.to_param, :ipc_boeing => { "ac_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ipc_boeing" do
      ipc_boeing = IpcBoeing.create! valid_attributes
      expect {
        delete :destroy, {:id => ipc_boeing.to_param}, valid_session
      }.to change(IpcBoeing, :count).by(-1)
    end

    it "redirects to the ipc_boeings list" do
      ipc_boeing = IpcBoeing.create! valid_attributes
      delete :destroy, {:id => ipc_boeing.to_param}, valid_session
      response.should redirect_to(ipc_boeings_url)
    end
  end

end
