require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SmpReferenzsController do

  # This should return the minimal set of attributes required to create a valid
  # SmpReferenz. As you add validations to SmpReferenz, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "spm_ref" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SmpReferenzsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all smp_referenzs as @smp_referenzs" do
      smp_referenz = SmpReferenz.create! valid_attributes
      get :index, {}, valid_session
      assigns(:smp_referenzs).should eq([smp_referenz])
    end
  end

  describe "GET show" do
    it "assigns the requested smp_referenz as @smp_referenz" do
      smp_referenz = SmpReferenz.create! valid_attributes
      get :show, {:id => smp_referenz.to_param}, valid_session
      assigns(:smp_referenz).should eq(smp_referenz)
    end
  end

  describe "GET new" do
    it "assigns a new smp_referenz as @smp_referenz" do
      get :new, {}, valid_session
      assigns(:smp_referenz).should be_a_new(SmpReferenz)
    end
  end

  describe "GET edit" do
    it "assigns the requested smp_referenz as @smp_referenz" do
      smp_referenz = SmpReferenz.create! valid_attributes
      get :edit, {:id => smp_referenz.to_param}, valid_session
      assigns(:smp_referenz).should eq(smp_referenz)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SmpReferenz" do
        expect {
          post :create, {:smp_referenz => valid_attributes}, valid_session
        }.to change(SmpReferenz, :count).by(1)
      end

      it "assigns a newly created smp_referenz as @smp_referenz" do
        post :create, {:smp_referenz => valid_attributes}, valid_session
        assigns(:smp_referenz).should be_a(SmpReferenz)
        assigns(:smp_referenz).should be_persisted
      end

      it "redirects to the created smp_referenz" do
        post :create, {:smp_referenz => valid_attributes}, valid_session
        response.should redirect_to(SmpReferenz.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved smp_referenz as @smp_referenz" do
        # Trigger the behavior that occurs when invalid params are submitted
        SmpReferenz.any_instance.stub(:save).and_return(false)
        post :create, {:smp_referenz => { "spm_ref" => "invalid value" }}, valid_session
        assigns(:smp_referenz).should be_a_new(SmpReferenz)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SmpReferenz.any_instance.stub(:save).and_return(false)
        post :create, {:smp_referenz => { "spm_ref" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested smp_referenz" do
        smp_referenz = SmpReferenz.create! valid_attributes
        # Assuming there are no other smp_referenzs in the database, this
        # specifies that the SmpReferenz created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SmpReferenz.any_instance.should_receive(:update).with({ "spm_ref" => "MyString" })
        put :update, {:id => smp_referenz.to_param, :smp_referenz => { "spm_ref" => "MyString" }}, valid_session
      end

      it "assigns the requested smp_referenz as @smp_referenz" do
        smp_referenz = SmpReferenz.create! valid_attributes
        put :update, {:id => smp_referenz.to_param, :smp_referenz => valid_attributes}, valid_session
        assigns(:smp_referenz).should eq(smp_referenz)
      end

      it "redirects to the smp_referenz" do
        smp_referenz = SmpReferenz.create! valid_attributes
        put :update, {:id => smp_referenz.to_param, :smp_referenz => valid_attributes}, valid_session
        response.should redirect_to(smp_referenz)
      end
    end

    describe "with invalid params" do
      it "assigns the smp_referenz as @smp_referenz" do
        smp_referenz = SmpReferenz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SmpReferenz.any_instance.stub(:save).and_return(false)
        put :update, {:id => smp_referenz.to_param, :smp_referenz => { "spm_ref" => "invalid value" }}, valid_session
        assigns(:smp_referenz).should eq(smp_referenz)
      end

      it "re-renders the 'edit' template" do
        smp_referenz = SmpReferenz.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SmpReferenz.any_instance.stub(:save).and_return(false)
        put :update, {:id => smp_referenz.to_param, :smp_referenz => { "spm_ref" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested smp_referenz" do
      smp_referenz = SmpReferenz.create! valid_attributes
      expect {
        delete :destroy, {:id => smp_referenz.to_param}, valid_session
      }.to change(SmpReferenz, :count).by(-1)
    end

    it "redirects to the smp_referenzs list" do
      smp_referenz = SmpReferenz.create! valid_attributes
      delete :destroy, {:id => smp_referenz.to_param}, valid_session
      response.should redirect_to(smp_referenzs_url)
    end
  end

end
